### ISSUE TITLE
Implement Webform functionality

### ISSUE THREAD

**Issue by genjohnson** [uiowa/sitenow#171]
Allow editors & webmasters to create/edit/delete webforms and access submissions, and automatically provide some spam protection.

The permissions should be configurable on a per-site basis, for example if on some site editors & webmasters should not have permission to create or edit webforms the permissions can be adjusted.

**Comment by joewhitsitt** [comment]
This is just a brain dump. I don't know if these are all possible in D8, but once customers get access to webform, these are the types of things I hear about.

- spam control
- open/close form
- hawkid authentication
- clone/duplicate a form
- download submissions (excel format does not work)
- confirmation page/redirection
- only form author (not all with webform permission) can see/download submissions of that particular form (i don't think this is currently an option or ITS would have it)
- email submission result to form owner, confirmation email to user (if email field).
- email link goes to access denied (user was not logged in when clicking the link)
- submission emails are delayed or never received.
- multiple file upload field (currently handled by allowing zip files, creating multiple file fields. formally handled by webform_multifile)
- written policy about PII, GDPR, etc.
- same form, multiple places.
- route email to certain address if X is selected/filled out.

**Comment by briand44** [comment]
#259
