### ISSUE TITLE
Investigate adding Admin Toolbar

### ISSUE THREAD

**Issue by bspeare** [uiowa/sitenow#195]
Is it possible to have the Admin Toolbar as the default admin menu (https://www.drupal.org/project/admin_toolbar)?

**Comment by joewhitsitt** [comment]
Personally I have no problem adding it, though I have no experience with it.

>Starting with 8.x-1.21 Admin Toolbar has become compliant with Section 508 of the Rehabilitation Act most notably by making the module keyboard accessible and compliant with color contrasts for focus.

I don't know what further steps need to be taken to be WCAG 2.0 compliant, but my guess is that would be the first sticking point for adoption.

Another question is whether or not it removes menu items based on permissions?

**Comment by richardbporter** [comment]
>Another question is whether or not it removes menu items based on permissions?

I wasn't seeing that on a UIHC site that used this module. 

Also, since it is not currently on the D7 SiteNow service, I think we'll pass on this.
