### ISSUE TITLE
Unmasqurade is not working.

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/sitenow#326]

**Comment by joewhitsitt** [comment]
unable to replicate in HR Stage:

<img width="191" alt="screen shot 2019-02-25 at 2 45 59 pm" src="https://user-images.githubusercontent.com/4663676/53367591-369a8d80-390c-11e9-8157-f3a0d48f968a.png">

**Comment by richardbporter** [comment]
I see two issues:

- Masquerading as administrator when logged in as an administrator results in the missing 'Unmasquerade' link.
- Logging in as a non-admin via `drush uli` results in the `Unmasquerade` link being present but not working.
