### ISSUE TITLE
Fatal error when adding a new page (/node/add/page)

### ISSUE THREAD

**Issue by pyrello** [uiowa/sitenow#335]
On a freshly installed site, when I visit /node/add/page, I get the following error:

```
Error: Call to undefined function section_alignitems_allowed_values() in options_allowed_values() (line 88 of core/modules/options/options.module).

options_allowed_values(Object, Object) (Line: 61)
Drupal\options\Plugin\Field\FieldType\ListItemBase->getSettableOptions(Object) (Line: 116)
Drupal\Core\Field\Plugin\Field\FieldWidget\OptionsWidgetBase->getOptions(Object) (Line: 34)
Drupal\Core\Field\Plugin\Field\FieldWidget\OptionsSelectWidget->formElement(Object, 0, Array, Array, Object) (Line: 335)
Drupal\Core\Field\WidgetBase->formSingleElement(Object, 0, Array, Array, Object) (Line: 85)
Drupal\Core\Field\WidgetBase->form(Object, Array, Object) (Line: 171)
Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm(Object, Array, Object) (Line: 760)
Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget->formElement(Object, 0, Array, Array, Object) (Line: 335)
Drupal\Core\Field\WidgetBase->formSingleElement(Object, 0, Array, Array, Object) (Line: 1086)
Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget->formMultipleElements(Object, Array, Object) (Line: 104)
Drupal\Core\Field\WidgetBase->form(Object, Array, Object, NULL) (Line: 1179)
Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget->form(Object, Array, Object) (Line: 171)
Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm(Object, Array, Object) (Line: 125)
Drupal\Core\Entity\ContentEntityForm->form(Array, Object) (Line: 115)
Drupal\node\NodeForm->form(Array, Object) (Line: 117)
Drupal\Core\Entity\EntityForm->buildForm(Array, Object)
call_user_func_array(Array, Array) (Line: 518)
Drupal\Core\Form\FormBuilder->retrieveForm('node_page_form', Object) (Line: 275)
Drupal\Core\Form\FormBuilder->buildForm('node_page_form', Object) (Line: 48)
Drupal\Core\Entity\EntityFormBuilder->getForm(Object) (Line: 113)
Drupal\node\Controller\NodeController->add(Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

I'm guessing this is an issue related to something not properly set during install related to the Section attributes. Any help is appreciated!

**Comment by adamdelaney** [comment]
This function should exist in uiowa_paragraphs.module, https://github.com/uiowa/sitenow/blob/53f762e7f701b41c9dd7400716550eb4325c6d81/modules/uiowa_paragraphs/uiowa_paragraphs.module#L285.

**Comment by pyrello** [comment]
The function is present in that module at exactly that line number. I'm at a loss for how to proceed, other than to run another site install to see if it doesn't happen again. But this is a freshly installed site with no modifications as-of-yet.

**Comment by adamdelaney** [comment]
Hmm, odd. Maybe try another install?

**Comment by pyrello** [comment]
Just tried another install, got this error again.

I updated uiowa again, so I should be up-to-date code-wise. I ran `lando destroy` and `lando rebuild` (which is probably overkill, but I wanted to make sure I was starting from as clean a starting point as possible). 

After that, from the `docroot/sites/grad.uiowa.edu` directory, I ran
```
lando drush si sitenow --sites-subdir=grad.uiowa.edu
lando drush uli
```

Clicked the link to automatically log in, then clicked the "Content" link in the admin menu, then clicked the "Add content" button. I got the same error as above.

**Comment by adamdelaney** [comment]
Might be easier to troubleshoot this in person. I'm not able to replicate this for a site-install.

**Comment by joewhitsitt** [comment]
Does it make a difference if you run the SI like `lando drush si sitenow --sites-subdir grad.uiowa.edu` without the equal sign? That is how I have been doing it all along.

I just did a fresh install/CR of grad.uiowa.edu locally after a uiowa pull/composer install and can't reproduce this error.

**Comment by pyrello** [comment]
@joewhitsitt That did not make a difference.

I've checked at the /admin/modules page, and the uiowa_paragraphs module is checked as being installed. I don't totally understand how this is happening, because it doesn't seem to be represented in the sitenow profile's config: https://github.com/uiowa/sitenow/blob/master/config/sync/core.extension.yml#L90

I'm at a loss here. I'm wondering if I need to just delete the whole application and start over again to make sure that there is no files somewhere that are out-of-date?

As a side note, I noticed that my local version of the hr.uiowa.edu site was out-of-date. Is there a process for updating the individual site projects? Or is that just done by navigating to those directories and running `git pull`?

**Comment by joewhitsitt** [comment]
My guess is it has to do with your local environment then as Adam and I can't reproduce. I also like to run my own sql-drop before I try to reinstall a site from scratch and a CR afterward just to make sure there isn't something lingering around.

The entry in core.extension is correct. I think the 0 designates weight that logic from that module fires. Removing an entry "uninstalls" the module.

HR has had breaking re-development done since December. A git pull of develop/master in the site directory gets the code base up to date and you should be able to do a new site install with it. I think there is an --existing-config flag way of doing this but @richardbporter would know more.

**Comment by pyrello** [comment]
I appreciate the help in trying to get this figured out. I think I'll try starting from scratch since I don't think I have any development wrapped up in this specific instance that I need to save. If that doesn't work, maybe I can drop by over there to see if we can troubleshoot?

**Comment by joewhitsitt** [comment]
Sounds fine.

**Comment by pyrello** [comment]
After starting over with a new install of uiowa/uiowa, I am no longer encountering this issue.

Its not that big of a deal, but I am curious if anyone has any insight into what might have gotten out of sync and why I wasn't able to re-establish an up-to-date baseline through `git pull`, `lando destroy`, and `lando rebuild`.
