### ISSUE TITLE
Investigate CSV redirect

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/sitenow#340]
https://www.drupal.org/project/path_redirect_import

**Comment by joewhitsitt** [comment]
Not a module and preformed by a developer:
https://gist.github.com/bserem/60160a3d932ef69ec85ff7b7c1aa3ce8

**Comment by joewhitsitt** [comment]
Instead of leaving a module installed on all the sites for this, I suggest for sites that need it to just create an update hook similar to this one: https://github.com/uiowa/hr.uiowa.edu/pull/26
